import { createFileRoute } from "@tanstack/react-router";
import { PageShell } from "@/components/site/PageShell";
import { Breadcrumb } from "@/components/site/Breadcrumb";
import { ShieldCheck, Lock, FileText, Phone, Cookie, UserCheck, BellRing, Database } from "lucide-react";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | BambiBoo Preschool & Daycare" },
      {
        name: "description",
        content:
          "Privacy Policy for BambiBoo Preschool & Daycare. Learn about how we collect, use, and protect your personal information.",
      },
      { property: "og:title", content: "Privacy Policy | BambiBoo Preschool & Daycare" },
      { property: "og:url", content: "/privacy" },
    ],
    links: [{ rel: "canonical", href: "/privacy" }],
  }),
  component: PrivacyPolicyPage,
});

const definitions = [
  { term: "Account", desc: "A unique account created for You to access Our Service or parts of Our Service." },
  { term: "Affiliate", desc: "An entity that controls, is controlled by, or is under common control with a party (50%+ ownership)." },
  { term: "Company", desc: "Refers to Bambiboo Preschool & Daycare, 44, 5th Main Rd, 1st Block Koramangala." },
  { term: "Cookies", desc: "Small files placed on your device containing browsing history details and preferences." },
  { term: "Country/State", desc: "Karnataka, India." },
  { term: "Device", desc: "Any device that can access the Service, such as a computer, cell phone, or digital tablet." },
  { term: "Personal Data", desc: "Any information that relates to an identified or identifiable individual." },
  { term: "Service", desc: "Refers to the Website (https://bambiboo.vercel.app/)." },
  { term: "Service Provider", desc: "Third-party companies or individuals employed by Company to facilitate and analyze the Service." },
  { term: "Usage Data", desc: "Data collected automatically, generated by the use of the Service or infrastructure." },
  { term: "User", desc: "Any individual who accesses or uses the Service." },
  { term: "Website", desc: "Bambiboo Preschool & Daycare, accessible from https://bambiboo.vercel.app/." },
  { term: "You", desc: "The individual accessing or using the Service, or legal entity on behalf of which such individual acts." },
];

function PrivacyPolicyPage() {
  return (
    <PageShell>
      {/* HERO BANNER SECTION */}
      <section className="relative overflow-hidden bg-[#FAFAFC] py-12 md:py-16 border-b border-border/60" data-no-reveal>
        <div className="absolute -top-20 -right-16 h-72 w-72 blob bg-primary/5 -z-10" />
        <div className="absolute -bottom-24 -left-10 h-64 w-64 blob bg-primary/5 -z-10" />
        <div className="container-page relative no-reveal" data-no-reveal>
          <Breadcrumb items={[{ label: "Privacy Policy" }]} className="mb-4 text-xs font-semibold text-primary/80" />
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-primary w-fit">
            <ShieldCheck className="h-4 w-4 text-primary" />
            Legal &amp; Privacy Transparency
          </div>
          <h1 className="mt-4 text-3xl md:text-5xl font-extrabold text-foreground tracking-tight text-balance">
            Privacy Policy
          </h1>
          <p className="mt-4 text-base md:text-lg text-foreground/90 leading-relaxed font-medium">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="mt-3 text-base md:text-lg text-foreground/90 leading-relaxed font-medium">
            We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required).
          </p>
        </div>
      </section>

      {/* SECTION 1: INTERPRETATION & DEFINITIONS */}
      <section className="py-12 md:py-16 bg-background border-b border-border/40" data-no-reveal>
        <div className="container-page no-reveal" data-no-reveal>
          <div className="w-full mb-8">
            <div className="text-xs font-bold uppercase tracking-widest text-primary">Key Terminology</div>
            <h2 className="mt-2 text-2xl md:text-3xl font-extrabold text-foreground">Interpretation and Definitions</h2>
            <p className="mt-2 text-sm md:text-base text-muted-foreground">
              The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {definitions.map((item) => (
              <div
                key={item.term}
                className="rounded-2xl border border-border/60 bg-white p-5 shadow-2xs hover:shadow-sm transition-all"
              >
                <div className="inline-block rounded-lg bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary mb-2">
                  {item.term}
                </div>
                <p className="text-xs sm:text-sm text-foreground/85 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 2: DATA COLLECTION & COOKIES */}
      <section className="py-12 md:py-16 bg-[#FAFAFC] border-b border-border/40" data-no-reveal>
        <div className="container-page no-reveal" data-no-reveal>
          <div className="w-full mb-10">
            <div className="text-xs font-bold uppercase tracking-widest text-primary">Information We Collect</div>
            <h2 className="mt-2 text-2xl md:text-3xl font-extrabold text-foreground">Collecting &amp; Using Your Personal Information</h2>
          </div>

          <div className="grid gap-8 lg:grid-cols-2 items-start">
            {/* Personal Data */}
            <div className="rounded-3xl border border-border/60 bg-white p-6 md:p-8 shadow-2xs space-y-4">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-2xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
                  <UserCheck className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-foreground">Personal Data</h3>
                  <p className="text-xs text-muted-foreground">Information you directly provide to us</p>
                </div>
              </div>
              <p className="text-sm text-foreground/85 leading-relaxed">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="space-y-2 pt-2">
                {["Email address", "First name and last name", "Phone number"].map((item) => (
                  <li key={item} className="flex items-center gap-2.5 text-sm font-semibold text-foreground/90">
                    <span className="h-2 w-2 rounded-full bg-primary shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>

              <div className="pt-4 border-t border-border/60 space-y-3">
                <h4 className="text-base font-bold text-foreground">Usage Data</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including the type of mobile device, unique ID, IP address, mobile OS, browser type, and diagnostic data.
                </p>
              </div>
            </div>

            {/* Cookies */}
            <div className="rounded-3xl border border-border/60 bg-white p-6 md:p-8 shadow-2xs space-y-4">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-2xl bg-amber-500/10 text-amber-600 flex items-center justify-center shrink-0">
                  <Cookie className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-foreground">Tracking Technologies &amp; Cookies</h3>
                  <p className="text-xs text-muted-foreground">How we ensure site functionality</p>
                </div>
              </div>
              <p className="text-sm text-foreground/85 leading-relaxed">
                We use tracking technologies (such as cookies) to track activity and improve Our Service:
              </p>
              <ul className="space-y-3 text-sm text-foreground/85 leading-relaxed">
                <li>
                  <strong className="text-foreground">Cookies or Browser Cookies:</strong> Small files placed on Your Device. You can instruct Your browser to refuse Cookies; however, some parts of Our Service may be affected.
                </li>
                <li>
                  <strong className="text-foreground">Web Beacons:</strong> Small electronic files (clear gifs, pixel tags) permitting us to count visitors and verify server integrity.
                </li>
              </ul>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Cookies can be "Persistent" or "Session" Cookies. Where required by law, non-essential cookies are used only with your consent, which can be withdrawn at any time.
              </p>

              <div className="space-y-3 pt-2">
                <div className="rounded-2xl bg-[#FAFAFC] border border-border/50 p-4 space-y-1">
                  <div className="text-xs font-bold text-primary uppercase">Necessary / Essential Cookies</div>
                  <p className="text-xs text-muted-foreground">Session Cookies administered by Us to provide essential services and prevent fraudulent use.</p>
                </div>
                <div className="rounded-2xl bg-[#FAFAFC] border border-border/50 p-4 space-y-1">
                  <div className="text-xs font-bold text-primary uppercase">Cookies Policy / Notice Acceptance</div>
                  <p className="text-xs text-muted-foreground">Persistent Cookies administered by Us to record your cookie preference choices on future visits.</p>
                </div>
                <div className="rounded-2xl bg-[#FAFAFC] border border-border/50 p-4 space-y-1">
                  <div className="text-xs font-bold text-primary uppercase">Functionality Cookies</div>
                  <p className="text-xs text-muted-foreground">Persistent Cookies administered by Us to remember login details and language preferences.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 3: USE OF YOUR PERSONAL DATA */}
      <section className="py-12 md:py-16 bg-background border-b border-border/40" data-no-reveal>
        <div className="container-page no-reveal" data-no-reveal>
          <div className="w-full mb-8">
            <div className="text-xs font-bold uppercase tracking-widest text-primary">Purpose &amp; Processing</div>
            <h2 className="mt-2 text-2xl md:text-3xl font-extrabold text-foreground">Use of Your Personal Data</h2>
            <p className="mt-2 text-sm md:text-base text-muted-foreground">
              The Company may use Personal Data for the following specific purposes:
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { title: "To Provide & Maintain Service", desc: "Including monitoring usage and site performance." },
              { title: "To Manage Your Account", desc: "Giving you access to specific user functionalities." },
              { title: "For Performance of Contract", desc: "Undertaking purchase contracts or agreements." },
              { title: "To Contact You", desc: "Via email, phone, SMS, or push notifications for security and updates." },
              { title: "News & Special Offers", desc: "Informing you about goods or events similar to past inquiries (opt-out available anytime)." },
              { title: "To Manage Requests", desc: "Attending to and managing all parent or customer requests." },
              { title: "Business Transfers", desc: "Evaluating or conducting mergers, sales, or restructuring." },
              { title: "Analytics & Improvements", desc: "Data analysis, usage trends, and promotional evaluation." },
            ].map((p) => (
              <div key={p.title} className="rounded-2xl border border-border/60 bg-white p-5 shadow-2xs space-y-2">
                <div className="text-sm font-bold text-foreground">{p.title}</div>
                <p className="text-xs text-muted-foreground leading-relaxed">{p.desc}</p>
              </div>
            ))}
          </div>

          <div className="mt-8 rounded-3xl border border-border/60 bg-white p-6 md:p-8 shadow-2xs space-y-4">
            <h3 className="text-lg font-bold text-foreground">Sharing Your Personal Data</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may share Your Personal Data in the following situations:
            </p>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 text-xs sm:text-sm text-foreground/85">
              <div className="rounded-xl bg-[#FAFAFC] p-3 border border-border/40">
                <strong>With Service Providers:</strong> To monitor and analyze Service use, and to contact You.
              </div>
              <div className="rounded-xl bg-[#FAFAFC] p-3 border border-border/40">
                <strong>For Business Transfers:</strong> During negotiations or completion of merger or asset sale.
              </div>
              <div className="rounded-xl bg-[#FAFAFC] p-3 border border-border/40">
                <strong>With Affiliates:</strong> Requiring affiliates, parent company, or subsidiaries to honor this policy.
              </div>
              <div className="rounded-xl bg-[#FAFAFC] p-3 border border-border/40">
                <strong>With Other Users:</strong> When interacting in public areas, information may be publicly viewed.
              </div>
              <div className="rounded-xl bg-[#FAFAFC] p-3 border border-border/40 sm:col-span-2 lg:col-span-2">
                <strong>With Your Consent:</strong> We may disclose Your Personal Data for any other purpose with Your explicit consent.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 4: TEXT MESSAGES PRIVACY NOTICE (SIGNATURE CALLOUT BOX) */}
      <section className="py-10 bg-[#FFF6D6] border-y border-amber-200" data-no-reveal>
        <div className="container-page no-reveal" data-no-reveal>
          <div className="flex flex-col md:flex-row items-start md:items-center gap-6">
            <div className="h-14 w-14 rounded-2xl bg-amber-400/20 text-[#4C167F] flex items-center justify-center shrink-0">
              <BellRing className="h-7 w-7" />
            </div>
            <div className="space-y-2 flex-1 text-[#231B32]">
              <div className="inline-block rounded-full bg-[#4C167F]/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-[#4C167F]">
                SMS &amp; Text Messaging Protection
              </div>
              <h3 className="text-xl font-extrabold text-[#4C167F]">Text Messages Privacy Notice</h3>
              <p className="text-sm leading-relaxed text-[#231B32]/90">
                You have the option to receive text (SMS) messages from Us regarding customer care, account notifications, status updates, OTP passcodes, security alerts, and offers.
              </p>
              <p className="text-sm font-bold text-[#4C167F]">
                No mobile information will be shared with or sold to third parties or affiliates for marketing or promotional purposes. Phone numbers and consent records collected for texting are never shared with anyone except technical delivery providers.
              </p>
              <div className="text-xs text-[#231B32]/80 font-medium pt-1">
                Reply <strong>STOP</strong> to opt-out. Reply <strong>HELP</strong> for support. Message &amp; data rates may apply. Messaging frequency may vary.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 5: DATA RETENTION, TRANSFER & DELETION */}
      <section className="py-12 md:py-16 bg-[#FAFAFC] border-b border-border/40" data-no-reveal>
        <div className="container-page no-reveal" data-no-reveal>
          <div className="grid gap-8 lg:grid-cols-3">
            {/* Retention */}
            <div className="rounded-3xl border border-border/60 bg-white p-6 shadow-2xs space-y-4">
              <div className="flex items-center gap-3">
                <Database className="h-6 w-6 text-primary" />
                <h3 className="text-lg font-bold text-foreground">Data Retention</h3>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                We retain Personal Data only for as long as necessary to fulfill legal obligations, resolve disputes, and enforce agreements.
              </p>
              <div className="space-y-2 text-xs text-foreground/85">
                <div className="p-3 bg-[#FAFAFC] rounded-xl border border-border/40">
                  <strong>User Accounts:</strong> Retained for account relationship plus up to 24 months post-closure.
                </div>
                <div className="p-3 bg-[#FAFAFC] rounded-xl border border-border/40">
                  <strong>Customer Support:</strong> Tickets &amp; chat transcripts up to 24 months.
                </div>
                <div className="p-3 bg-[#FAFAFC] rounded-xl border border-border/40">
                  <strong>Analytics &amp; Logs:</strong> Cookies, IP logs up to 24 months for security.
                </div>
              </div>
            </div>

            {/* Transfer */}
            <div className="rounded-3xl border border-border/60 bg-white p-6 shadow-2xs space-y-4">
              <div className="flex items-center gap-3">
                <Lock className="h-6 w-6 text-primary" />
                <h3 className="text-lg font-bold text-foreground">Data Transfer</h3>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Your information is processed at operating offices and locations where parties involved are located. Where required by law, international transfers of Personal Data are subject to appropriate safeguards and strict security controls.
              </p>
              <div className="p-3 bg-[#FAFAFC] rounded-xl border border-border/40 text-xs text-foreground/85">
                No transfer of Your Personal Data takes place without adequate security controls in place.
              </div>
            </div>

            {/* Deletion */}
            <div className="rounded-3xl border border-border/60 bg-white p-6 shadow-2xs space-y-4">
              <div className="flex items-center gap-3">
                <FileText className="h-6 w-6 text-primary" />
                <h3 className="text-lg font-bold text-foreground">Delete Your Data</h3>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                You have the right to delete or request assistance in deleting collected Personal Data.
              </p>
              <p className="text-xs text-foreground/85 leading-relaxed">
                You may update, amend, or delete Your information anytime by signing in to account settings or contacting Us directly. Certain data may be retained when required by legal obligations.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 6: DISCLOSURE, SECURITY, MINORS & UPDATES */}
      <section className="py-12 md:py-16 bg-background" data-no-reveal>
        <div className="container-page no-reveal" data-no-reveal>
          <div className="grid gap-8 md:grid-cols-2">
            <div className="rounded-3xl border border-border/60 bg-white p-6 md:p-8 shadow-2xs space-y-4">
              <h3 className="text-xl font-bold text-foreground">Disclosure &amp; Security</h3>
              <div className="space-y-3 text-sm text-foreground/85 leading-relaxed">
                <p>
                  <strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition, or asset sale, Notice will be provided before transfer.
                </p>
                <p>
                  <strong>Law Enforcement:</strong> We may disclose data if required by law or valid public authority requests.
                </p>
                <p>
                  <strong>Security:</strong> We use commercially reasonable safeguards to protect Personal Data, though no electronic storage method is 100% immune.
                </p>
              </div>
            </div>

            <div className="rounded-3xl border border-border/60 bg-white p-6 md:p-8 shadow-2xs space-y-4">
              <h3 className="text-xl font-bold text-foreground">Children's Privacy &amp; Policy Updates</h3>
              <div className="space-y-3 text-sm text-foreground/85 leading-relaxed">
                <p>
                  <strong>Children's Privacy:</strong> The Service is not directed to anyone under 16 without parental/guardian consent. If you believe a child under 16 provided us data, contact us to remove it.
                </p>
                <p>
                  <strong>External Links:</strong> We advise reviewing privacy policies of third-party websites accessed via links on our Service.
                </p>
                <p>
                  <strong>Policy Changes:</strong> We will notify you of updates by posting the new policy on this page or via email/notice.
                </p>
              </div>
            </div>
          </div>

          {/* CONTACT BOX */}
          <div className="mt-10 rounded-3xl border border-primary/20 bg-primary/5 p-6 md:p-8 text-center max-w-xl mx-auto space-y-4">
            <h3 className="text-xl font-extrabold text-foreground">Have questions about this Privacy Policy?</h3>
            <p className="text-sm text-muted-foreground">
              Our administrative team is here to assist you with any privacy or data protection inquiries.
            </p>
            <a
              href="tel:+919900639303"
              className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground shadow-md hover:bg-primary/90 transition-all"
            >
              <Phone className="h-4 w-4" />
              Call Us: +91 99006 39303
            </a>
          </div>
        </div>
      </section>
    </PageShell>
  );
}
