/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BeyondIndexRouteImport } from './routes/beyond.index'
import { Route as BeyondArtsRouteImport } from './routes/beyond.arts'
import { Route as BeyondFestivalsRouteImport } from './routes/beyond.festivals'
import { Route as BeyondFieldTripsRouteImport } from './routes/beyond.field-trips'
import { Route as BeyondMusicRouteImport } from './routes/beyond.music'
import { Route as BeyondYogaRouteImport } from './routes/beyond.yoga'
import { Route as BlogsPostIdRouteImport } from './routes/blogs.$postId'
import { Route as BlogsPreschoolReadinessguideRouteImport } from './routes/blogs.preschool-readinessguide'
import { Route as ParentsIndexRouteImport } from './routes/parents.index'
import { Route as ParentsAdmissionRouteImport } from './routes/parents.admission'
import { Route as ParentsCurriculumRouteImport } from './routes/parents.curriculum'
import { Route as ParentsDailyRoutineRouteImport } from './routes/parents.daily-routine'
import { Route as ParentsFaqRouteImport } from './routes/parents.faq'
import { Route as ParentsFoodRouteImport } from './routes/parents.food'
import { Route as ParentsSafetyRouteImport } from './routes/parents.safety'
import { Route as ParentsTestimonialsRouteImport } from './routes/parents.testimonials'
import { Route as ParentsTransportRouteImport } from './routes/parents.transport'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesDaycareRouteImport } from './routes/programmes.daycare'
import { Route as ProgrammesHobbyCenterRouteImport } from './routes/programmes.hobby-center'
import { Route as ProgrammesLkgRouteImport } from './routes/programmes.lkg'
import { Route as ProgrammesNurseryRouteImport } from './routes/programmes.nursery'
import { Route as ProgrammesParentToddlerRouteImport } from './routes/programmes.parent-toddler'
import { Route as ProgrammesPlaygroupRouteImport } from './routes/programmes.playgroup'
import { Route as ProgrammesPreschoolRouteImport } from './routes/programmes.preschool'
import { Route as ProgrammesUkgRouteImport } from './routes/programmes.ukg'
import { Route as WorldIndexRouteImport } from './routes/world.index'
import { Route as WorldAtHomeRouteImport } from './routes/world.at-home'
import { Route as WorldGalleryRouteImport } from './routes/world.gallery'
import { Route as WorldIndoorRouteImport } from './routes/world.indoor'
import { Route as WorldOutdoorRouteImport } from './routes/world.outdoor'
import { Route as WorldSteamRouteImport } from './routes/world.steam'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondIndexRoute = BeyondIndexRouteImport.update({
  id: '/beyond/',
  path: '/beyond/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondArtsRoute = BeyondArtsRouteImport.update({
  id: '/beyond/arts',
  path: '/beyond/arts',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondFestivalsRoute = BeyondFestivalsRouteImport.update({
  id: '/beyond/festivals',
  path: '/beyond/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondFieldTripsRoute = BeyondFieldTripsRouteImport.update({
  id: '/beyond/field-trips',
  path: '/beyond/field-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondMusicRoute = BeyondMusicRouteImport.update({
  id: '/beyond/music',
  path: '/beyond/music',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondYogaRoute = BeyondYogaRouteImport.update({
  id: '/beyond/yoga',
  path: '/beyond/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsPostIdRoute = BlogsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsPreschoolReadinessguideRoute =
  BlogsPreschoolReadinessguideRouteImport.update({
    id: '/preschool-readinessguide',
    path: '/preschool-readinessguide',
    getParentRoute: () => BlogsRoute,
  } as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsAdmissionRoute = ParentsAdmissionRouteImport.update({
  id: '/parents/admission',
  path: '/parents/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsCurriculumRoute = ParentsCurriculumRouteImport.update({
  id: '/parents/curriculum',
  path: '/parents/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsDailyRoutineRoute = ParentsDailyRoutineRouteImport.update({
  id: '/parents/daily-routine',
  path: '/parents/daily-routine',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsFaqRoute = ParentsFaqRouteImport.update({
  id: '/parents/faq',
  path: '/parents/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsFoodRoute = ParentsFoodRouteImport.update({
  id: '/parents/food',
  path: '/parents/food',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsSafetyRoute = ParentsSafetyRouteImport.update({
  id: '/parents/safety',
  path: '/parents/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsTestimonialsRoute = ParentsTestimonialsRouteImport.update({
  id: '/parents/testimonials',
  path: '/parents/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsTransportRoute = ParentsTransportRouteImport.update({
  id: '/parents/transport',
  path: '/parents/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesDaycareRoute = ProgrammesDaycareRouteImport.update({
  id: '/programmes/daycare',
  path: '/programmes/daycare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesHobbyCenterRoute = ProgrammesHobbyCenterRouteImport.update({
  id: '/programmes/hobby-center',
  path: '/programmes/hobby-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesLkgRoute = ProgrammesLkgRouteImport.update({
  id: '/programmes/lkg',
  path: '/programmes/lkg',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesNurseryRoute = ProgrammesNurseryRouteImport.update({
  id: '/programmes/nursery',
  path: '/programmes/nursery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesParentToddlerRoute = ProgrammesParentToddlerRouteImport.update({
  id: '/programmes/parent-toddler',
  path: '/programmes/parent-toddler',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesPlaygroupRoute = ProgrammesPlaygroupRouteImport.update({
  id: '/programmes/playgroup',
  path: '/programmes/playgroup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesPreschoolRoute = ProgrammesPreschoolRouteImport.update({
  id: '/programmes/preschool',
  path: '/programmes/preschool',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesUkgRoute = ProgrammesUkgRouteImport.update({
  id: '/programmes/ukg',
  path: '/programmes/ukg',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIndexRoute = WorldIndexRouteImport.update({
  id: '/world/',
  path: '/world/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldAtHomeRoute = WorldAtHomeRouteImport.update({
  id: '/world/at-home',
  path: '/world/at-home',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldGalleryRoute = WorldGalleryRouteImport.update({
  id: '/world/gallery',
  path: '/world/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIndoorRoute = WorldIndoorRouteImport.update({
  id: '/world/indoor',
  path: '/world/indoor',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldOutdoorRoute = WorldOutdoorRouteImport.update({
  id: '/world/outdoor',
  path: '/world/outdoor',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldSteamRoute = WorldSteamRouteImport.update({
  id: '/world/steam',
  path: '/world/steam',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/beyond/arts': typeof BeyondArtsRoute
  '/beyond/festivals': typeof BeyondFestivalsRoute
  '/beyond/field-trips': typeof BeyondFieldTripsRoute
  '/beyond/music': typeof BeyondMusicRoute
  '/beyond/yoga': typeof BeyondYogaRoute
  '/blogs/$postId': typeof BlogsPostIdRoute
  '/blogs/preschool-readinessguide': typeof BlogsPreschoolReadinessguideRoute
  '/parents/admission': typeof ParentsAdmissionRoute
  '/parents/curriculum': typeof ParentsCurriculumRoute
  '/parents/daily-routine': typeof ParentsDailyRoutineRoute
  '/parents/faq': typeof ParentsFaqRoute
  '/parents/food': typeof ParentsFoodRoute
  '/parents/safety': typeof ParentsSafetyRoute
  '/parents/testimonials': typeof ParentsTestimonialsRoute
  '/parents/transport': typeof ParentsTransportRoute
  '/programmes/daycare': typeof ProgrammesDaycareRoute
  '/programmes/hobby-center': typeof ProgrammesHobbyCenterRoute
  '/programmes/lkg': typeof ProgrammesLkgRoute
  '/programmes/nursery': typeof ProgrammesNurseryRoute
  '/programmes/parent-toddler': typeof ProgrammesParentToddlerRoute
  '/programmes/playgroup': typeof ProgrammesPlaygroupRoute
  '/programmes/preschool': typeof ProgrammesPreschoolRoute
  '/programmes/ukg': typeof ProgrammesUkgRoute
  '/world/at-home': typeof WorldAtHomeRoute
  '/world/gallery': typeof WorldGalleryRoute
  '/world/indoor': typeof WorldIndoorRoute
  '/world/outdoor': typeof WorldOutdoorRoute
  '/world/steam': typeof WorldSteamRoute
  '/beyond/': typeof BeyondIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/world/': typeof WorldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/beyond/arts': typeof BeyondArtsRoute
  '/beyond/festivals': typeof BeyondFestivalsRoute
  '/beyond/field-trips': typeof BeyondFieldTripsRoute
  '/beyond/music': typeof BeyondMusicRoute
  '/beyond/yoga': typeof BeyondYogaRoute
  '/blogs/$postId': typeof BlogsPostIdRoute
  '/blogs/preschool-readinessguide': typeof BlogsPreschoolReadinessguideRoute
  '/parents/admission': typeof ParentsAdmissionRoute
  '/parents/curriculum': typeof ParentsCurriculumRoute
  '/parents/daily-routine': typeof ParentsDailyRoutineRoute
  '/parents/faq': typeof ParentsFaqRoute
  '/parents/food': typeof ParentsFoodRoute
  '/parents/safety': typeof ParentsSafetyRoute
  '/parents/testimonials': typeof ParentsTestimonialsRoute
  '/parents/transport': typeof ParentsTransportRoute
  '/programmes/daycare': typeof ProgrammesDaycareRoute
  '/programmes/hobby-center': typeof ProgrammesHobbyCenterRoute
  '/programmes/lkg': typeof ProgrammesLkgRoute
  '/programmes/nursery': typeof ProgrammesNurseryRoute
  '/programmes/parent-toddler': typeof ProgrammesParentToddlerRoute
  '/programmes/playgroup': typeof ProgrammesPlaygroupRoute
  '/programmes/preschool': typeof ProgrammesPreschoolRoute
  '/programmes/ukg': typeof ProgrammesUkgRoute
  '/world/at-home': typeof WorldAtHomeRoute
  '/world/gallery': typeof WorldGalleryRoute
  '/world/indoor': typeof WorldIndoorRoute
  '/world/outdoor': typeof WorldOutdoorRoute
  '/world/steam': typeof WorldSteamRoute
  '/beyond': typeof BeyondIndexRoute
  '/parents': typeof ParentsIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/world': typeof WorldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/beyond/arts': typeof BeyondArtsRoute
  '/beyond/festivals': typeof BeyondFestivalsRoute
  '/beyond/field-trips': typeof BeyondFieldTripsRoute
  '/beyond/music': typeof BeyondMusicRoute
  '/beyond/yoga': typeof BeyondYogaRoute
  '/blogs/$postId': typeof BlogsPostIdRoute
  '/blogs/preschool-readinessguide': typeof BlogsPreschoolReadinessguideRoute
  '/parents/admission': typeof ParentsAdmissionRoute
  '/parents/curriculum': typeof ParentsCurriculumRoute
  '/parents/daily-routine': typeof ParentsDailyRoutineRoute
  '/parents/faq': typeof ParentsFaqRoute
  '/parents/food': typeof ParentsFoodRoute
  '/parents/safety': typeof ParentsSafetyRoute
  '/parents/testimonials': typeof ParentsTestimonialsRoute
  '/parents/transport': typeof ParentsTransportRoute
  '/programmes/daycare': typeof ProgrammesDaycareRoute
  '/programmes/hobby-center': typeof ProgrammesHobbyCenterRoute
  '/programmes/lkg': typeof ProgrammesLkgRoute
  '/programmes/nursery': typeof ProgrammesNurseryRoute
  '/programmes/parent-toddler': typeof ProgrammesParentToddlerRoute
  '/programmes/playgroup': typeof ProgrammesPlaygroupRoute
  '/programmes/preschool': typeof ProgrammesPreschoolRoute
  '/programmes/ukg': typeof ProgrammesUkgRoute
  '/world/at-home': typeof WorldAtHomeRoute
  '/world/gallery': typeof WorldGalleryRoute
  '/world/indoor': typeof WorldIndoorRoute
  '/world/outdoor': typeof WorldOutdoorRoute
  '/world/steam': typeof WorldSteamRoute
  '/beyond/': typeof BeyondIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/world/': typeof WorldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/sitemap.xml'
    | '/beyond/arts'
    | '/beyond/festivals'
    | '/beyond/field-trips'
    | '/beyond/music'
    | '/beyond/yoga'
    | '/blogs/$postId'
    | '/blogs/preschool-readinessguide'
    | '/parents/admission'
    | '/parents/curriculum'
    | '/parents/daily-routine'
    | '/parents/faq'
    | '/parents/food'
    | '/parents/safety'
    | '/parents/testimonials'
    | '/parents/transport'
    | '/programmes/daycare'
    | '/programmes/hobby-center'
    | '/programmes/lkg'
    | '/programmes/nursery'
    | '/programmes/parent-toddler'
    | '/programmes/playgroup'
    | '/programmes/preschool'
    | '/programmes/ukg'
    | '/world/at-home'
    | '/world/gallery'
    | '/world/indoor'
    | '/world/outdoor'
    | '/world/steam'
    | '/beyond/'
    | '/parents/'
    | '/programmes/'
    | '/world/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/sitemap.xml'
    | '/beyond/arts'
    | '/beyond/festivals'
    | '/beyond/field-trips'
    | '/beyond/music'
    | '/beyond/yoga'
    | '/blogs/$postId'
    | '/blogs/preschool-readinessguide'
    | '/parents/admission'
    | '/parents/curriculum'
    | '/parents/daily-routine'
    | '/parents/faq'
    | '/parents/food'
    | '/parents/safety'
    | '/parents/testimonials'
    | '/parents/transport'
    | '/programmes/daycare'
    | '/programmes/hobby-center'
    | '/programmes/lkg'
    | '/programmes/nursery'
    | '/programmes/parent-toddler'
    | '/programmes/playgroup'
    | '/programmes/preschool'
    | '/programmes/ukg'
    | '/world/at-home'
    | '/world/gallery'
    | '/world/indoor'
    | '/world/outdoor'
    | '/world/steam'
    | '/beyond'
    | '/parents'
    | '/programmes'
    | '/world'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/sitemap.xml'
    | '/beyond/arts'
    | '/beyond/festivals'
    | '/beyond/field-trips'
    | '/beyond/music'
    | '/beyond/yoga'
    | '/blogs/$postId'
    | '/blogs/preschool-readinessguide'
    | '/parents/admission'
    | '/parents/curriculum'
    | '/parents/daily-routine'
    | '/parents/faq'
    | '/parents/food'
    | '/parents/safety'
    | '/parents/testimonials'
    | '/parents/transport'
    | '/programmes/daycare'
    | '/programmes/hobby-center'
    | '/programmes/lkg'
    | '/programmes/nursery'
    | '/programmes/parent-toddler'
    | '/programmes/playgroup'
    | '/programmes/preschool'
    | '/programmes/ukg'
    | '/world/at-home'
    | '/world/gallery'
    | '/world/indoor'
    | '/world/outdoor'
    | '/world/steam'
    | '/beyond/'
    | '/parents/'
    | '/programmes/'
    | '/world/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BeyondArtsRoute: typeof BeyondArtsRoute
  BeyondFestivalsRoute: typeof BeyondFestivalsRoute
  BeyondFieldTripsRoute: typeof BeyondFieldTripsRoute
  BeyondMusicRoute: typeof BeyondMusicRoute
  BeyondYogaRoute: typeof BeyondYogaRoute
  ParentsAdmissionRoute: typeof ParentsAdmissionRoute
  ParentsCurriculumRoute: typeof ParentsCurriculumRoute
  ParentsDailyRoutineRoute: typeof ParentsDailyRoutineRoute
  ParentsFaqRoute: typeof ParentsFaqRoute
  ParentsFoodRoute: typeof ParentsFoodRoute
  ParentsSafetyRoute: typeof ParentsSafetyRoute
  ParentsTestimonialsRoute: typeof ParentsTestimonialsRoute
  ParentsTransportRoute: typeof ParentsTransportRoute
  ProgrammesDaycareRoute: typeof ProgrammesDaycareRoute
  ProgrammesHobbyCenterRoute: typeof ProgrammesHobbyCenterRoute
  ProgrammesLkgRoute: typeof ProgrammesLkgRoute
  ProgrammesNurseryRoute: typeof ProgrammesNurseryRoute
  ProgrammesParentToddlerRoute: typeof ProgrammesParentToddlerRoute
  ProgrammesPlaygroupRoute: typeof ProgrammesPlaygroupRoute
  ProgrammesPreschoolRoute: typeof ProgrammesPreschoolRoute
  ProgrammesUkgRoute: typeof ProgrammesUkgRoute
  WorldAtHomeRoute: typeof WorldAtHomeRoute
  WorldGalleryRoute: typeof WorldGalleryRoute
  WorldIndoorRoute: typeof WorldIndoorRoute
  WorldOutdoorRoute: typeof WorldOutdoorRoute
  WorldSteamRoute: typeof WorldSteamRoute
  BeyondIndexRoute: typeof BeyondIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  WorldIndexRoute: typeof WorldIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond/': {
      id: '/beyond/'
      path: '/beyond'
      fullPath: '/beyond/'
      preLoaderRoute: typeof BeyondIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond/arts': {
      id: '/beyond/arts'
      path: '/beyond/arts'
      fullPath: '/beyond/arts'
      preLoaderRoute: typeof BeyondArtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond/festivals': {
      id: '/beyond/festivals'
      path: '/beyond/festivals'
      fullPath: '/beyond/festivals'
      preLoaderRoute: typeof BeyondFestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond/field-trips': {
      id: '/beyond/field-trips'
      path: '/beyond/field-trips'
      fullPath: '/beyond/field-trips'
      preLoaderRoute: typeof BeyondFieldTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond/music': {
      id: '/beyond/music'
      path: '/beyond/music'
      fullPath: '/beyond/music'
      preLoaderRoute: typeof BeyondMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond/yoga': {
      id: '/beyond/yoga'
      path: '/beyond/yoga'
      fullPath: '/beyond/yoga'
      preLoaderRoute: typeof BeyondYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$postId': {
      id: '/blogs/$postId'
      path: '/$postId'
      fullPath: '/blogs/$postId'
      preLoaderRoute: typeof BlogsPostIdRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/preschool-readinessguide': {
      id: '/blogs/preschool-readinessguide'
      path: '/preschool-readinessguide'
      fullPath: '/blogs/preschool-readinessguide'
      preLoaderRoute: typeof BlogsPreschoolReadinessguideRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/admission': {
      id: '/parents/admission'
      path: '/parents/admission'
      fullPath: '/parents/admission'
      preLoaderRoute: typeof ParentsAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/curriculum': {
      id: '/parents/curriculum'
      path: '/parents/curriculum'
      fullPath: '/parents/curriculum'
      preLoaderRoute: typeof ParentsCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/daily-routine': {
      id: '/parents/daily-routine'
      path: '/parents/daily-routine'
      fullPath: '/parents/daily-routine'
      preLoaderRoute: typeof ParentsDailyRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/faq': {
      id: '/parents/faq'
      path: '/parents/faq'
      fullPath: '/parents/faq'
      preLoaderRoute: typeof ParentsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/food': {
      id: '/parents/food'
      path: '/parents/food'
      fullPath: '/parents/food'
      preLoaderRoute: typeof ParentsFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/safety': {
      id: '/parents/safety'
      path: '/parents/safety'
      fullPath: '/parents/safety'
      preLoaderRoute: typeof ParentsSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/testimonials': {
      id: '/parents/testimonials'
      path: '/parents/testimonials'
      fullPath: '/parents/testimonials'
      preLoaderRoute: typeof ParentsTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/transport': {
      id: '/parents/transport'
      path: '/parents/transport'
      fullPath: '/parents/transport'
      preLoaderRoute: typeof ParentsTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/daycare': {
      id: '/programmes/daycare'
      path: '/programmes/daycare'
      fullPath: '/programmes/daycare'
      preLoaderRoute: typeof ProgrammesDaycareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/hobby-center': {
      id: '/programmes/hobby-center'
      path: '/programmes/hobby-center'
      fullPath: '/programmes/hobby-center'
      preLoaderRoute: typeof ProgrammesHobbyCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/lkg': {
      id: '/programmes/lkg'
      path: '/programmes/lkg'
      fullPath: '/programmes/lkg'
      preLoaderRoute: typeof ProgrammesLkgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/nursery': {
      id: '/programmes/nursery'
      path: '/programmes/nursery'
      fullPath: '/programmes/nursery'
      preLoaderRoute: typeof ProgrammesNurseryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/parent-toddler': {
      id: '/programmes/parent-toddler'
      path: '/programmes/parent-toddler'
      fullPath: '/programmes/parent-toddler'
      preLoaderRoute: typeof ProgrammesParentToddlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/playgroup': {
      id: '/programmes/playgroup'
      path: '/programmes/playgroup'
      fullPath: '/programmes/playgroup'
      preLoaderRoute: typeof ProgrammesPlaygroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/preschool': {
      id: '/programmes/preschool'
      path: '/programmes/preschool'
      fullPath: '/programmes/preschool'
      preLoaderRoute: typeof ProgrammesPreschoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/ukg': {
      id: '/programmes/ukg'
      path: '/programmes/ukg'
      fullPath: '/programmes/ukg'
      preLoaderRoute: typeof ProgrammesUkgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/': {
      id: '/world/'
      path: '/world'
      fullPath: '/world/'
      preLoaderRoute: typeof WorldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/at-home': {
      id: '/world/at-home'
      path: '/world/at-home'
      fullPath: '/world/at-home'
      preLoaderRoute: typeof WorldAtHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/gallery': {
      id: '/world/gallery'
      path: '/world/gallery'
      fullPath: '/world/gallery'
      preLoaderRoute: typeof WorldGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/indoor': {
      id: '/world/indoor'
      path: '/world/indoor'
      fullPath: '/world/indoor'
      preLoaderRoute: typeof WorldIndoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/outdoor': {
      id: '/world/outdoor'
      path: '/world/outdoor'
      fullPath: '/world/outdoor'
      preLoaderRoute: typeof WorldOutdoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/steam': {
      id: '/world/steam'
      path: '/world/steam'
      fullPath: '/world/steam'
      preLoaderRoute: typeof WorldSteamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsPostIdRoute: typeof BlogsPostIdRoute
  BlogsPreschoolReadinessguideRoute: typeof BlogsPreschoolReadinessguideRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsPostIdRoute: BlogsPostIdRoute,
  BlogsPreschoolReadinessguideRoute: BlogsPreschoolReadinessguideRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BeyondArtsRoute: BeyondArtsRoute,
  BeyondFestivalsRoute: BeyondFestivalsRoute,
  BeyondFieldTripsRoute: BeyondFieldTripsRoute,
  BeyondMusicRoute: BeyondMusicRoute,
  BeyondYogaRoute: BeyondYogaRoute,
  ParentsAdmissionRoute: ParentsAdmissionRoute,
  ParentsCurriculumRoute: ParentsCurriculumRoute,
  ParentsDailyRoutineRoute: ParentsDailyRoutineRoute,
  ParentsFaqRoute: ParentsFaqRoute,
  ParentsFoodRoute: ParentsFoodRoute,
  ParentsSafetyRoute: ParentsSafetyRoute,
  ParentsTestimonialsRoute: ParentsTestimonialsRoute,
  ParentsTransportRoute: ParentsTransportRoute,
  ProgrammesDaycareRoute: ProgrammesDaycareRoute,
  ProgrammesHobbyCenterRoute: ProgrammesHobbyCenterRoute,
  ProgrammesLkgRoute: ProgrammesLkgRoute,
  ProgrammesNurseryRoute: ProgrammesNurseryRoute,
  ProgrammesParentToddlerRoute: ProgrammesParentToddlerRoute,
  ProgrammesPlaygroupRoute: ProgrammesPlaygroupRoute,
  ProgrammesPreschoolRoute: ProgrammesPreschoolRoute,
  ProgrammesUkgRoute: ProgrammesUkgRoute,
  WorldAtHomeRoute: WorldAtHomeRoute,
  WorldGalleryRoute: WorldGalleryRoute,
  WorldIndoorRoute: WorldIndoorRoute,
  WorldOutdoorRoute: WorldOutdoorRoute,
  WorldSteamRoute: WorldSteamRoute,
  BeyondIndexRoute: BeyondIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  WorldIndexRoute: WorldIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
